### ISSUE TITLE
gcc 7 toolchain (macos anyway)

### ISSUE THREAD

**Issue by hrbrmstr** [Ironholds/rgeolocate#41]
it's not building with gcc 7 toolchain but still does with old one. CRAN does not have a binary for 3.4 for macOS and that's likely due to the gcc 7 thing. i'll hit you up at work abt it.

**Comment by wrathematics** [comment]
Builds for me in gcc 7 on Linux. The CRAN check error is clang related.

I fixed some of the compiler warnings in the latest gcc and clang.  I do not consider them real warnings; they were recently added to clang because of an error specific to MS compilers, and gcc has apparently decided to follow suit.  As much as I may disagree with their reasoning, it's not a hard fix.  However, I am unable to open pull requests at the moment. I get a strange error every time: ![gh](https://cloud.githubusercontent.com/assets/2561297/26039296/27677084-38e7-11e7-8a60-593b7a38910a.png)

The error looks like something wrong with github.

gcc 7 has a few additional compiler warnings that actually are serious.  The maxmind folks don't check `fread()` return values.  You can add some boilerplate to suppress the warnings, but I don't see a simple path to error handling.  I would recommend reporting this to the maintainers (or ignoring it I guess).

**Comment by oschwald** [comment]
AFAIK, we don't use `fread()`; it is all mmap based. Do you have a link to the build log?

**Comment by wrathematics** [comment]
Oh you're right! My mistake. It's in another included library.

**Comment by hrbrmstr** [comment]
I'll post the macOS build issues in the AM. in the middle of work-work at the moment (thx to WannCry)

**Comment by Ironholds** [comment]
I believe https://github.com/chrislim2888/IP2Location-C-Library would be the other included lib?

**Comment by Ironholds** [comment]
This last patch should've fixed it, and I'll pass the changes over to the ip2location people too
