### ISSUE TITLE
rgeolocate error limiting my R functionality

### ISSUE THREAD

**Issue by j-p-courneya** [Ironholds/rgeolocate#48]
Hi, Sorry if this is not the right forum for reporting Im still new to communicating through GitHub. I have been having an issue with rgeolocate for a few days now. when i launched Rstudio i got a loadnamespace error related to rgeolocate. So i tried installing and this was what I did: 

`
> install.packages("rgeolocate")
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘rgeolocate’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘rgeolocate’
trying URL https://cran.rstudio.com/src/contrib/rgeolocate_1.0.1.tar.gz
Content type 'application/x-gzip' length 1331328 bytes (1.3 MB)
==================================================
downloaded 1.3 MB
Error in loadNamespace("rgeolocate") : 
  there is no package called ‘rgeolocate’
Execution halted
Warning in install.packages :
  installation of package ‘rgeolocate’ had non-zero exit status
The downloaded source packages are in
‘/private/var/folders/pp/spw6j7fn6_z7756v5z7s5thc0000gp/T/RtmpVa4vMh/downloaded_packages’

I have been scratching my head over this quite a bit and am not sure why the package doesnt install. i saw a bug thread in this repo and read through the thread but couldn't figure out what the fix was for `rgeolocate`. 

Im running OSX High Sierra 10.13.2, i have installed xcode from dev tools. 

> R.Version()
$platform
[1] "x86_64-apple-darwin15.6.0"
$arch
[1] "x86_64"
$os
[1] "darwin15.6.0"
$system
[1] "x86_64, darwin15.6.0"
$status
[1] ""
$major
[1] "3"
$minor
[1] "4.3"
$year
[1] "2017"
$month
[1] "11"
$day
[1] "30"
$`svn rev`
[1] "73796"
$language
[1] "R"
$version.string
[1] "R version 3.4.3 (2017-11-30)"
$nickname
[1] "Kite-Eating Tree"

It may be worth mentioning that i had run into issues compiling from source for "rattle" package which relied on C compilation. and this seems to be similar.

Im considering running R in Debian VM because i hear that is more reliable. thanks for any assistance you can provide!

**Comment by Ironholds** [comment]
Same as #45 , maybe? Does it output any more error than that?

**Comment by zhudanyang008** [comment]
Hi, I also got the same problem. Even after I installed the 'rgeolocation' package, everytime when I launch my Rstudio, the same error message appears. Also, if I attempt to knit, the same error message pops up, like this:

> Error in loadNamespace("rgeolocate") : 
>   there is no package called ‘rgeolocate’


Then I check whether this package is installed in the right directory. Unfortunately, this time another type of error message pops up, like this:

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   object 'vI' not found

I really don't know how to deal with this problem.
I remembered that it was last year when the High Sierra unknown timezone bug came out, I tried the codes from a blogger. That was the first time that I tried to install the 'rgeolocation' package.

> setme <- 
> "Sys.setenv(TZ='America/New_York') #some default not get any errors
> invisible(loadNamespace('rgeolocate'))
> invisible(loadNamespace('httr'))
> mytz <- rgeolocate::ip_api(httr::content(httr::GET('https://api.ipify.org?format=json'))[1])[['timezone']]
> Sys.setenv(TZ=mytz)"
> 
> cat(setme,file=file.path(R.home(),'etc/Rprofile.site'),sep='\n')
> 
> https://community.rstudio.com/t/rstudio-sys-setenv-does-not-persist/2105

Ever since that, I got this problem. The High Sierra problem is now fixed in R version 3.4.3, but I still cannot get rid of this error loadNamespace message. Could you please give me some suggestions?

**Comment by Ironholds** [comment]
Does the RStudio packages panel say the package is installed?

**Comment by zhudanyang008** [comment]
Hi Oliver! Thank you for your response.
No. I cannot find it in the installed list even after I manually move the
package folder to the right directory where other packages are stored.
I don’t need ‘rgeolocation’ package now, and I didn’t type anything about
installing a certain package in the R console. However, the error message
just stick around, telling me that ‘Error in the Namespace’ or something
like that. I have no idea how to deal with this because nothing changes
after I reinstall R and R studio. Do you have any possible solutions or
suggestions?

D

**Comment by Ironholds** [comment]
Ok, in no particular order:

1. This is very clearly a different bug from the originally reported bug in this thread. In the future it would be good to ensure that this is reflected by it being a separate issue.
2. This is not a bug with rgeolocate
3. I would really strongly recommend not manually moving package folder to directories.
4. The reason you're getting these errors is because you modified your Rprofile file to call rgeolocate every time you load R, and whether you have R installed or not, *that* setting has stayed around.
5. Go to whichever file is produced from `file.path(R.home(),'etc/Rprofile.site')` and remove all the code you added, including the rgeolocate call. Make sure you just remove the code you added; that file is used for a variety of stuff.

**Comment by zhudanyang008** [comment]
Hi Oliver,

Thanks a lot for your explanation. I think I might unconsciously modify the
Rstudio setup by adding some codes in Rstudio because I am a beginner in R
programming. I just want to double check with you to see whether this is
the code that you mentioned to be deleted?  I opened the "Rprofile.site"
with R and attached is the page with codes. I really appreciate your help.

Best,

Danyang

**Comment by Ironholds** [comment]
Hey Danyang,

I don't see any attached file (email attachments don't transfer over, I'm afraid) but it's the code you added in your timezone command:

```
"Sys.setenv(TZ='America/New_York') #some default not get any errors
invisible(loadNamespace('rgeolocate'))
invisible(loadNamespace('httr'))
mytz <- rgeolocate::ip_api(httr::content(httr::GET('https://api.ipify.org?format=json'))[1])[['timezone']]
Sys.setenv(TZ=mytz)
```

**Comment by zhudanyang008** [comment]
Hi Oliver,

Exactly. That's the contents in my Rprofile.site file after I opened it in
R. So am I supposed to delete all these codes from the Rprofile.site?


Thank you,

Danyang

**Comment by zhudanyang008** [comment]
Hi Oliver,


I did that and it worked out quite well. I am writing to let you know that
I really appreciate your time and patience.

Have a great weekend!


Best,

Danyang

**Comment by Ironholds** [comment]
No problem! Glad I could help :)

**Comment by Ironholds** [comment]
And @j-p-courneya any update on my questions?

**Comment by j-p-courneya** [comment]
dear @Ironholds apologies for letting this fall through the cracks. i am going to close it as i have completely lost touch with my issue and am not on that machine. However i greatly appreciate the questions that have prompted me to consider some alternate behaviors in my package management practices.
